
services:
  postgres:
    container_name: postgres-sql-whatsapp-clone
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: whatsapp-clone   # DB name
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - whatsapp-clone
    restart: unless-stopped

  keycloak:
    container_name: keycloak-whatsapp-clone
    image: quay.io/keycloak/keycloak:26.0.0
    ports:
      - 9090:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
    networks:
      - whatsapp-clone
    command:
      - "start-dev"   # Will start keycloak server for us

networks:
  whatsapp-clone:
    driver: bridge

volumes:
  postgres:
    driver: local
